### ISSUE TITLE
Impossible d'ouvrir Prix-carburant.obf

### ISSUE THREAD

**Issue by Codain** [cbosdo/gas-price#2]
Le fichier téléchargé (http://bosdonnat.fr/osmand-fuel/Prix-carburant.obf) ne fait que 64 octets et ne peut être lu par OsmAnd. Par avance merci pour le correctif.

**Comment by cbosdo** [comment]
oops, je ne vois l'issue que maintenant... mais je n'utilise plus la branche pour Osmand: je suis passé sur organic maps.
